### ISSUE TITLE
purple grass with biome mods

### ISSUE THREAD

**Issue by Thefatsparrow** [lucaargolo/fabric-seasons#101]
as it says purple grass witch isnt very realistic a good fix for it would be to be able to adjust the value of the colour from a menu maybe like other mods for different seasons

**Comment by lucaargolo** [comment]
Heyy. As of version 2.0 all colormaps have been remade. Also I'm currently working on custom compatibility packs for biome mods so that shouldn't be an issues anymore. Here's all currently available compatibility packs:
https://github.com/lucaargolo/fabric-seasons-terralith-compat
https://github.com/lucaargolo/fabric-seasons-byg-compat

**Comment by Thefatsparrow** [comment]
thanks man your amazin
